import = ["/Users/pgk/dotfiles/base/alacritty/themes/current.toml"]
live_config_reload = true

[env]
TERM = "xterm-256color"

[font]
size = 15

[font.bold]
family = "Inconsolata Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Inconsolata Nerd Font"
style = "Bold Italic"

[font.italic]
family = "Inconsolata Nerd Font"
style = "Italic"

[font.normal]
family = "Inconsolata Nerd Font"
style = "Regular"

[shell]
program = "/bin/bash"
